### ISSUE TITLE
MiSTer_misc.sh fails to install mbc

### ISSUE THREAD

**Issue by Mellified** [pocomane/MiSTer_misc#1]
Running `MiSTer_misc.sh` from the Scripts directory or via SSH session reports no errors. The process creates the `/media/fat/misc/MiSTer_Batch_Control/` directory, but does not copy the mbc executable to this directory. `/media/fat/misc/MiSTer_Batch_Control/` is also not added to the linux path, making command line usage tedious.

**Comment by pocomane** [comment]
I hope that the empty-dir issue was fixed in the [last](https://github.com/pocomane/MiSTer_misc/commit/ad5d8a418ee29e7cddc30f5f1b0b0403cf5fcf6c) commit.
Thanks for the report!

**Comment by pocomane** [comment]
Now also the PATH issue should be resolved. I added a linked to mbc in the Script directory, that is by default in the PATH.

**Comment by Mellified** [comment]
Fixes confirmed.
