### ISSUE TITLE
Failed to run command Mister_WebMenu: Permission denied

### ISSUE THREAD

**Issue by cmcginty** [pocomane/MiSTer_misc#2]
Got this error trying to start the webmenu after running the installer script:

```
/media/fat/Scripts# bash -x webmenu_start.sh
+ cd /media/fat/misc/MiSTer_webmenu_package
+ /media/fat/misc/MiSTer_webmenu_package/hook/action/start.sh
nohup: failed to run command '../MiSTer_WebMenu': Permission denied
+ EXIT_CODE=0
+ read -n 1 -s -r -p 'Press any key to continue'
Press any key to continue
```

**Comment by pocomane** [comment]
It seems you have an old version of the MiSTer_webmenu_package. Indeed in the very first version, it searched for the  exectutable `../MiSTer_WebMenu`, but the newer version searches for `../MiSTer_WebMenu/MiSTer_WebMenu` that is where MiSTer_misc place it.

Did you update recently MiSTer_misc (e.g. calling `curl -L -k "https://raw.githubusercontent.com/pocomane/MiSTer_misc/master/MiSTer_misc.sh" | bash -s update`)? This should update all the package to the new version.

EDIT. Sorry, now I realize that "after running the installer script" probably means that you just updated MiSTer_misc. However you got the old start script... this is weird, I will try to reproduce this on my system to understand what is happening.

**Comment by pocomane** [comment]
There was an issue with the webmenu package repo: the wrong release was tagged as "Latest". I will investigate on why it was tagged in this way, however for the moment I forced a new release that is correctly tagged. So now if you run a MiSTer_misc update you should be able to run WebMenu from the installed script.

Let me now if this fix the issue. And thanks for the bug report!

**Comment by cmcginty** [comment]
Yes, updating fixed the issue now.
